### ISSUE TITLE
[Bug] tidak dapat click pada halaman setelah tekan save pada modal

### ISSUE THREAD

**Issue by haganrowlens** [Aplikasi-Sidang-PoltekPos/SimProBugReport#4]
setelah melakukan submit form pada modal dengan menekan save, tombol tombol pada halaman yang sedang terbuka tidak dapat di click
![3](https://user-images.githubusercontent.com/65953191/82894932-9a7f8c00-9f7d-11ea-9883-512ac8a50029.PNG)

**Comment by haganz753** [comment]
Terimakasih atas responnya, bug akan segera diatasi

**Comment by haganz753** [comment]
done fix
